backend:
  name: git-gateway
  repo: rebeccawshaw/church.nyc
  branch: netlify-cms

publish_mode: editorial_workflow

media_folder: "static/images" # Media files will be stored in the repo under static/images
public_folder: "/images" # The src attribute for uploaded media will begin with /images

collections:
  - name: "sermons" # Used in routes, e.g., /admin/collections/sermons
    label: "Sermons" # Used in the UI
    folder: "static/sermons" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    media_folder: ''
    public_folder: ''
    path: '{{series}}/{{slug}}'
    fields: # The fields for each document, usually in front matter
      - {label: "Layout", name: "layout", widget: "hidden", default: "blog"}
      - {label: "Series", name: "series", widget: "string"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Featured Image", name: "thumbnail", widget: "image"}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "pages"
    label: "Pages"
    folder: "static/pages"
    create: true
    slug: "{{slug}}"
    media_folder: ''
    public_folder: ''
    path: 'pages/{{slug}}'
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "page"}

      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Featured Image", name: "thumbnail", widget: "image"}
      - {label: "Body", name: "body", widget: "markdown"}